spring:
   profiles:
      active: ${SPRING_PROFILES_ACTIVE:h2}
   main:
      web-application-type: none
   autoconfigure:
    exclude: org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
   liquibase:
      enabled: false 
      